apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        upstream minio-api {
            zone minio-api 64k;
            server 192.168.2.249:9000 max_fails=2 fail_timeout=10s;
            server 192.168.2.250:9000 max_fails=2 fail_timeout=10s;
            server 192.168.2.251:9000 max_fails=2 fail_timeout=10s;
            server 192.168.2.252:9000 max_fails=2 fail_timeout=10s;
        }

        upstream minio-web {
            zone minio-web 64k;
            server 192.168.2.249:9001 max_fails=2 fail_timeout=10s;
            server 192.168.2.250:9001 max_fails=2 fail_timeout=10s;
            server 192.168.2.251:9001 max_fails=2 fail_timeout=10s;
            server 192.168.2.252:9001 max_fails=2 fail_timeout=10s;
        }

        server {
            listen 80;
            server_name minio-api-cluster.lbjt;

            location / {
                proxy_pass http://minio-api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /healthz {
                access_log off;
                return 200 'OK';
                add_header Content-Type text/plain;
            }
        }

        server {
            listen 80;
            server_name minio-web-cluster.lbjt;

            location / {
                proxy_pass http://minio-web;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /healthz {
                access_log off;
                return 200 'OK';
                add_header Content-Type text/plain;
            }
        }
    }
